"""Add is_resubmission to AvailabilityRequest

Revision ID: 122eb8a46a94
Revises: 158608ae5ab6
Create Date: 2025-06-04 23:16:44.365449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122eb8a46a94'
down_revision = '158608ae5ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resubmission', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability_request', schema=None) as batch_op:
        batch_op.drop_column('is_resubmission')

    # ### end Alembic commands ###
