"""Add AvailabilityRequest table

Revision ID: 158608ae5ab6
Revises: 9d4bc91df649
Create Date: 2025-06-02 22:44:29.278001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158608ae5ab6'
down_revision = '9d4bc91df649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time_of_day', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability_request')
    # ### end Alembic commands ###
