"""Refactor Notification model

Revision ID: 4a48115b3060
Revises: 59fca873e29b
Create Date: 2025-06-11 12:28:10.868107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a48115b3060'
down_revision = '59fca873e29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('notification_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('notification_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['recipient_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])
        batch_op.drop_column('staff_id')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('staff_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notification_ibfk_2'), 'user', ['admin_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('notification_ibfk_1'), 'user', ['staff_id'], ['id'])
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
