"""Add attempted_username and user_agent to login_activity

Revision ID: 59fca873e29b
Revises: 881cb47e46eb
Create Date: 2025-06-10 12:46:36.755010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fca873e29b'
down_revision = '881cb47e46eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempted_username', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_activity', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('attempted_username')

    # ### end Alembic commands ###
