"""Add is_active to AvailabilityRequest

Revision ID: 868fa3de91cc
Revises: 122eb8a46a94
Create Date: 2025-06-05 00:07:15.444627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868fa3de91cc'
down_revision = '122eb8a46a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability_request', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
