"""Add login_activity table

Revision ID: 881cb47e46eb
Revises: 56d25902cdb1
Create Date: 2025-06-10 03:54:12.617348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881cb47e46eb'
down_revision = '56d25902cdb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_activity')
    # ### end Alembic commands ###
