"""Add desired_shift to schedule_request

Revision ID: a9cff5548de8
Revises: 188ec4536243
Create Date: 2025-06-05 03:59:57.504241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cff5548de8'
down_revision = '188ec4536243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desired_shift', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_request', schema=None) as batch_op:
        batch_op.drop_column('desired_shift')

    # ### end Alembic commands ###
